helmDefaults:
  wait: true
  timeout: 600
missingFileHandler: Warn
values:
  - "values.yaml"
  - "values.gotmpl"
releases:
  - name: strimzi-drain-cleaner
    namespace: "{{ .Values.kafkaNamespace }}"
    labels:
      type: remote
      update_scc: true
      isbranch: false
      stream: master
      repoURL: ssh://jenkins@gerrit.mdtu-ddm-edp-cicd:32114/mdtu-ddm/devops/strimzi-drain-cleaner.git
      path: components/infra/
      branch: 1.5.0-SNAPSHOT.5
    chart: '{{ env "CUSTOM_BASEDIR" | default "/opt" }}/repositories/components/infra/strimzi-drain-cleaner.git/deploy-templates'
    version: 1.5.0-SNAPSHOT.5
    values:
      - values.yaml
      - values.gotmpl
      - image:
          name: '{{ env "edpComponentDockerRegistryUrl" }}/{{ env "globalEDPProject" }}/strimzi-drain-cleaner-master'
          version: 1.5.0-SNAPSHOT.5
    missingFileHandler: Warn
  - name: kafka-operator
    namespace: "{{ .Values.kafkaNamespace }}"
    labels:
      type: remote
      update_scc: true
      isbranch: false
      stream: master
      repoURL: ssh://jenkins@gerrit.mdtu-ddm-edp-cicd:32114/mdtu-ddm/devops/operators/kafka-operator.git
      path: components/infra/
      branch: 1.5.0-SNAPSHOT.4
    chart: '{{ env "CUSTOM_BASEDIR" | default "/opt" }}/repositories/components/infra/kafka-operator.git/deploy-templates'
    version: 1.5.0-SNAPSHOT.4
    values:
      - "values.yaml"
      - "values.gotmpl"
      - image:
          name: '{{ env "edpComponentDockerRegistryUrl" }}/{{ env "globalEDPProject" }}/kafka-operator-master'
          version: 1.5.0-SNAPSHOT.4
    missingFileHandler: Warn