helmDefaults:
  wait: true
  timeout: 600
missingFileHandler: Warn
values:
  - "values.yaml"
  - "values.gotmpl"
releases:
  - name: strimzi-drain-cleaner
    namespace: "{{ .Values.kafkaNamespace }}"
    labels:
      type: remote
      update_scc: true
      isbranch: false
      repoURL: ssh://jenkins@gerrit.mdtu-ddm-edp-cicd:32114/mdtu-ddm/devops/strimzi-drain-cleaner.git
      path: components/infra/
    chart: '{{ env "CUSTOM_BASEDIR" | default "/opt" }}/repositories/components/infra/strimzi-drain-cleaner.git/deploy-templates'
    version: 1.9.8.1
    values:
      - values.yaml
      - values.gotmpl
    missingFileHandler: Warn
  - name: kafka-operator
    namespace: "{{ .Values.kafkaNamespace }}"
    labels:
      type: remote
      update_scc: true
      isbranch: false
      repoURL: ssh://jenkins@gerrit.mdtu-ddm-edp-cicd:32114/mdtu-ddm/devops/operators/kafka-operator.git
      path: components/infra/
    chart: '{{ env "CUSTOM_BASEDIR" | default "/opt" }}/repositories/components/infra/kafka-operator.git/deploy-templates'
    version: 1.9.8.1
    values:
      - "values.yaml"
      - "values.gotmpl"
    missingFileHandler: Warn
